### ISSUE TITLE
Best use case and dependencies?

### ISSUE THREAD

**Issue by ghost** [DylanYasen/unity-ability-system#2]
This is a system I keep coming back to reference cause it looks sound. I'm trying to figure out how to create an ability system for a 3d shooter. However it doesn't seem like courotines are my best option to use. What is in the profile class? What does it represent?

**Comment by DylanYasen** [comment]
you dont have to use coroutine. it just makes sequencing things easier compare to keeping an internal timer.    

profile just caches components of the object (so dont have to  getcomponent<> everytime)

anyways , this thing is at least 5 year old, and not maintained
